server:
  port: 8080

spring:
  application:
    name: SupplierAndWholesalerLian

  datasource:
    url: jdbc:mysql://localhost/lian
    username: root
    password: erick123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true